<?php

/**
 * @file
 * Hooks for Date Recur Modular Widget Framework.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function date_recur_modular_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'date_recur_modular_alpha_widget' => [
      'render element' => 'widget',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * HOOK: 'date_recur_modular_widget'.
 */
function date_recur_modular_preprocess_date_recur_modular_alpha_widget(array &$variables): void {
  $variables['attributes']['class'][] = 'date-recur-modular-alpha-widget';
  $variables['#attached']['library'][] = 'date_recur_modular/date_recur_modular_alpha_widget';
}
